#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v7
# autospec commit: f56f1fa
#
# Source0 file verified with key 0x6211EBF1EFBADFBC (jack@randombit.net)
#
Name     : compat-Botan-soname2
Version  : 3.3.0
Release  : 40
URL      : https://botan.randombit.net/releases/Botan-3.3.0.tar.xz
Source0  : https://botan.randombit.net/releases/Botan-3.3.0.tar.xz
Source1  : https://botan.randombit.net/releases/Botan-3.3.0.tar.xz.asc
Summary  : Crypto and TLS for Modern C++
Group    : Development/Tools
License  : BSD-2-Clause
Requires: compat-Botan-soname2-lib = %{version}-%{release}
Requires: compat-Botan-soname2-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : bzip2-dev
BuildRequires : openssl-dev
BuildRequires : xz-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Add-more-autoconf-compatibility-options.patch
Patch2: 0002-Enable-genentropy-3-on-Linux.patch

%description
Botan: Crypto and TLS for Modern C++
========================================
Botan (Japanese for peony flower) is a C++ cryptography library released under the
permissive `Simplified BSD <https://botan.randombit.net/license.txt>`_ license.

%package lib
Summary: lib components for the compat-Botan-soname2 package.
Group: Libraries
Requires: compat-Botan-soname2-license = %{version}-%{release}

%description lib
lib components for the compat-Botan-soname2 package.


%package license
Summary: license components for the compat-Botan-soname2 package.
Group: Default

%description license
license components for the compat-Botan-soname2 package.


%prep
%setup -q -n Botan-3.3.0
cd %{_builddir}/Botan-3.3.0
%patch -P 1 -p1
%patch -P 2 -p1

%build
## build_prepend content
ln -s configure.py configure
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1712610801
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --enable-modules=bzip2,zlib,lzma \
--with-debug-info \
--disable-modules=camellia,`sed -n '1,/<prohibited>/d;/<\/prohibited>/{x;s/\n/,/gp};s/#.*//;/^$/d;H' src/build-data/policy/modern.txt`
make  %{?_smp_mflags}

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1712610801
rm -rf %{buildroot}
## install_prepend content
sed -i 's/env python/env python3/' src/scripts/install.py
## install_prepend end
mkdir -p %{buildroot}/usr/share/package-licenses/compat-Botan-soname2
cp %{_builddir}/Botan-%{version}/license.txt %{buildroot}/usr/share/package-licenses/compat-Botan-soname2/746f79eacfdbe5f1af1553042b17fc2c3c1c59c7 || :
export GOAMD64=v2
GOAMD64=v2
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/bin/botan
rm -f %{buildroot}*/usr/include/botan-3/botan/aead.h
rm -f %{buildroot}*/usr/include/botan-3/botan/allocator.h
rm -f %{buildroot}*/usr/include/botan-3/botan/argon2.h
rm -f %{buildroot}*/usr/include/botan-3/botan/argon2fmt.h
rm -f %{buildroot}*/usr/include/botan-3/botan/asn1_obj.h
rm -f %{buildroot}*/usr/include/botan-3/botan/asn1_print.h
rm -f %{buildroot}*/usr/include/botan-3/botan/assert.h
rm -f %{buildroot}*/usr/include/botan-3/botan/auto_rng.h
rm -f %{buildroot}*/usr/include/botan-3/botan/base32.h
rm -f %{buildroot}*/usr/include/botan-3/botan/base58.h
rm -f %{buildroot}*/usr/include/botan-3/botan/base64.h
rm -f %{buildroot}*/usr/include/botan-3/botan/bcrypt.h
rm -f %{buildroot}*/usr/include/botan-3/botan/bcrypt_pbkdf.h
rm -f %{buildroot}*/usr/include/botan-3/botan/ber_dec.h
rm -f %{buildroot}*/usr/include/botan-3/botan/bigint.h
rm -f %{buildroot}*/usr/include/botan-3/botan/block_cipher.h
rm -f %{buildroot}*/usr/include/botan-3/botan/buf_comp.h
rm -f %{buildroot}*/usr/include/botan-3/botan/build.h
rm -f %{buildroot}*/usr/include/botan-3/botan/bzip2.h
rm -f %{buildroot}*/usr/include/botan-3/botan/certstor.h
rm -f %{buildroot}*/usr/include/botan-3/botan/certstor_flatfile.h
rm -f %{buildroot}*/usr/include/botan-3/botan/certstor_sql.h
rm -f %{buildroot}*/usr/include/botan-3/botan/certstor_system.h
rm -f %{buildroot}*/usr/include/botan-3/botan/chacha_rng.h
rm -f %{buildroot}*/usr/include/botan-3/botan/cipher_mode.h
rm -f %{buildroot}*/usr/include/botan-3/botan/compiler.h
rm -f %{buildroot}*/usr/include/botan-3/botan/compression.h
rm -f %{buildroot}*/usr/include/botan-3/botan/concepts.h
rm -f %{buildroot}*/usr/include/botan-3/botan/credentials_manager.h
rm -f %{buildroot}*/usr/include/botan-3/botan/curve25519.h
rm -f %{buildroot}*/usr/include/botan-3/botan/curve_gfp.h
rm -f %{buildroot}*/usr/include/botan-3/botan/data_snk.h
rm -f %{buildroot}*/usr/include/botan-3/botan/data_src.h
rm -f %{buildroot}*/usr/include/botan-3/botan/database.h
rm -f %{buildroot}*/usr/include/botan-3/botan/der_enc.h
rm -f %{buildroot}*/usr/include/botan-3/botan/dh.h
rm -f %{buildroot}*/usr/include/botan-3/botan/dilithium.h
rm -f %{buildroot}*/usr/include/botan-3/botan/dl_group.h
rm -f %{buildroot}*/usr/include/botan-3/botan/dlies.h
rm -f %{buildroot}*/usr/include/botan-3/botan/dsa.h
rm -f %{buildroot}*/usr/include/botan-3/botan/ec_group.h
rm -f %{buildroot}*/usr/include/botan-3/botan/ec_point.h
rm -f %{buildroot}*/usr/include/botan-3/botan/ecc_key.h
rm -f %{buildroot}*/usr/include/botan-3/botan/ecdh.h
rm -f %{buildroot}*/usr/include/botan-3/botan/ecdsa.h
rm -f %{buildroot}*/usr/include/botan-3/botan/ecgdsa.h
rm -f %{buildroot}*/usr/include/botan-3/botan/ecies.h
rm -f %{buildroot}*/usr/include/botan-3/botan/eckcdsa.h
rm -f %{buildroot}*/usr/include/botan-3/botan/ed25519.h
rm -f %{buildroot}*/usr/include/botan-3/botan/entropy_src.h
rm -f %{buildroot}*/usr/include/botan-3/botan/exceptn.h
rm -f %{buildroot}*/usr/include/botan-3/botan/fd_unix.h
rm -f %{buildroot}*/usr/include/botan-3/botan/ffi.h
rm -f %{buildroot}*/usr/include/botan-3/botan/filter.h
rm -f %{buildroot}*/usr/include/botan-3/botan/filters.h
rm -f %{buildroot}*/usr/include/botan-3/botan/fpe_fe1.h
rm -f %{buildroot}*/usr/include/botan-3/botan/frodo_mode.h
rm -f %{buildroot}*/usr/include/botan-3/botan/frodokem.h
rm -f %{buildroot}*/usr/include/botan-3/botan/hash.h
rm -f %{buildroot}*/usr/include/botan-3/botan/hex.h
rm -f %{buildroot}*/usr/include/botan-3/botan/hmac_drbg.h
rm -f %{buildroot}*/usr/include/botan-3/botan/kdf.h
rm -f %{buildroot}*/usr/include/botan-3/botan/kyber.h
rm -f %{buildroot}*/usr/include/botan-3/botan/lzma.h
rm -f %{buildroot}*/usr/include/botan-3/botan/mac.h
rm -f %{buildroot}*/usr/include/botan-3/botan/mceliece.h
rm -f %{buildroot}*/usr/include/botan-3/botan/mem_ops.h
rm -f %{buildroot}*/usr/include/botan-3/botan/mutex.h
rm -f %{buildroot}*/usr/include/botan-3/botan/nist_keywrap.h
rm -f %{buildroot}*/usr/include/botan-3/botan/numthry.h
rm -f %{buildroot}*/usr/include/botan-3/botan/ocsp.h
rm -f %{buildroot}*/usr/include/botan-3/botan/oids.h
rm -f %{buildroot}*/usr/include/botan-3/botan/otp.h
rm -f %{buildroot}*/usr/include/botan-3/botan/p11.h
rm -f %{buildroot}*/usr/include/botan-3/botan/p11_ecc_key.h
rm -f %{buildroot}*/usr/include/botan-3/botan/p11_ecdh.h
rm -f %{buildroot}*/usr/include/botan-3/botan/p11_ecdsa.h
rm -f %{buildroot}*/usr/include/botan-3/botan/p11_object.h
rm -f %{buildroot}*/usr/include/botan-3/botan/p11_randomgenerator.h
rm -f %{buildroot}*/usr/include/botan-3/botan/p11_rsa.h
rm -f %{buildroot}*/usr/include/botan-3/botan/p11_types.h
rm -f %{buildroot}*/usr/include/botan-3/botan/p11_x509.h
rm -f %{buildroot}*/usr/include/botan-3/botan/pbkdf.h
rm -f %{buildroot}*/usr/include/botan-3/botan/pbkdf2.h
rm -f %{buildroot}*/usr/include/botan-3/botan/pem.h
rm -f %{buildroot}*/usr/include/botan-3/botan/pgp_s2k.h
rm -f %{buildroot}*/usr/include/botan-3/botan/pipe.h
rm -f %{buildroot}*/usr/include/botan-3/botan/pk_algs.h
rm -f %{buildroot}*/usr/include/botan-3/botan/pk_keys.h
rm -f %{buildroot}*/usr/include/botan-3/botan/pk_ops.h
rm -f %{buildroot}*/usr/include/botan-3/botan/pk_ops_fwd.h
rm -f %{buildroot}*/usr/include/botan-3/botan/pkcs10.h
rm -f %{buildroot}*/usr/include/botan-3/botan/pkcs11.h
rm -f %{buildroot}*/usr/include/botan-3/botan/pkcs11f.h
rm -f %{buildroot}*/usr/include/botan-3/botan/pkcs11t.h
rm -f %{buildroot}*/usr/include/botan-3/botan/pkcs8.h
rm -f %{buildroot}*/usr/include/botan-3/botan/pkix_enums.h
rm -f %{buildroot}*/usr/include/botan-3/botan/pkix_types.h
rm -f %{buildroot}*/usr/include/botan-3/botan/processor_rng.h
rm -f %{buildroot}*/usr/include/botan-3/botan/psk_db.h
rm -f %{buildroot}*/usr/include/botan-3/botan/pubkey.h
rm -f %{buildroot}*/usr/include/botan-3/botan/pwdhash.h
rm -f %{buildroot}*/usr/include/botan-3/botan/reducer.h
rm -f %{buildroot}*/usr/include/botan-3/botan/rfc3394.h
rm -f %{buildroot}*/usr/include/botan-3/botan/rfc4880.h
rm -f %{buildroot}*/usr/include/botan-3/botan/rng.h
rm -f %{buildroot}*/usr/include/botan-3/botan/roughtime.h
rm -f %{buildroot}*/usr/include/botan-3/botan/rsa.h
rm -f %{buildroot}*/usr/include/botan-3/botan/scrypt.h
rm -f %{buildroot}*/usr/include/botan-3/botan/secmem.h
rm -f %{buildroot}*/usr/include/botan-3/botan/sm2.h
rm -f %{buildroot}*/usr/include/botan-3/botan/sodium.h
rm -f %{buildroot}*/usr/include/botan-3/botan/sp_parameters.h
rm -f %{buildroot}*/usr/include/botan-3/botan/sphincsplus.h
rm -f %{buildroot}*/usr/include/botan-3/botan/srp6.h
rm -f %{buildroot}*/usr/include/botan-3/botan/stateful_rng.h
rm -f %{buildroot}*/usr/include/botan-3/botan/stream_cipher.h
rm -f %{buildroot}*/usr/include/botan-3/botan/strong_type.h
rm -f %{buildroot}*/usr/include/botan-3/botan/sym_algo.h
rm -f %{buildroot}*/usr/include/botan-3/botan/symkey.h
rm -f %{buildroot}*/usr/include/botan-3/botan/system_rng.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_alert.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_algos.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_callbacks.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_channel.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_ciphersuite.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_client.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_exceptn.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_extensions.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_external_psk.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_handshake_msg.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_magic.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_messages.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_policy.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_psk_identity_13.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_server.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_server_info.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_session.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_session_manager.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_session_manager_hybrid.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_session_manager_memory.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_session_manager_noop.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_session_manager_sql.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_session_manager_stateless.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_signature_scheme.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tls_version.h
rm -f %{buildroot}*/usr/include/botan-3/botan/tss.h
rm -f %{buildroot}*/usr/include/botan-3/botan/types.h
rm -f %{buildroot}*/usr/include/botan-3/botan/uuid.h
rm -f %{buildroot}*/usr/include/botan-3/botan/version.h
rm -f %{buildroot}*/usr/include/botan-3/botan/x509_ca.h
rm -f %{buildroot}*/usr/include/botan-3/botan/x509_crl.h
rm -f %{buildroot}*/usr/include/botan-3/botan/x509_ext.h
rm -f %{buildroot}*/usr/include/botan-3/botan/x509_key.h
rm -f %{buildroot}*/usr/include/botan-3/botan/x509_obj.h
rm -f %{buildroot}*/usr/include/botan-3/botan/x509cert.h
rm -f %{buildroot}*/usr/include/botan-3/botan/x509path.h
rm -f %{buildroot}*/usr/include/botan-3/botan/x509self.h
rm -f %{buildroot}*/usr/include/botan-3/botan/xmss.h
rm -f %{buildroot}*/usr/include/botan-3/botan/xmss_parameters.h
rm -f %{buildroot}*/usr/include/botan-3/botan/xof.h
rm -f %{buildroot}*/usr/include/botan-3/botan/zfec.h
rm -f %{buildroot}*/usr/include/botan-3/botan/zlib.h
rm -f %{buildroot}*/usr/lib64/cmake/Botan-3.3.0/botan-config-version.cmake
rm -f %{buildroot}*/usr/lib64/cmake/Botan-3.3.0/botan-config.cmake
rm -f %{buildroot}*/usr/lib64/libbotan-3.so
rm -f %{buildroot}*/usr/lib64/pkgconfig/botan-3.pc
rm -f %{buildroot}*/usr/lib64/python3.12/site-packages/botan3.py
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/authors.txt
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/abi.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/bigint.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/block_cipher.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/cipher_modes.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/compression.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/contents.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/credentials_manager.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/cryptobox.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/ecc.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/env_vars.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/ffi.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/filters.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/footguns.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/fpe.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/hash.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/kdf.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/keywrap.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/message_auth_codes.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/otp.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/passhash.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/pbkdf.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/pkcs11.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/providers.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/psk_db.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/pubkey.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/python.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/rng.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/roughtime.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/secmem.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/srp.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/stream_ciphers.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/tls.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/tpm.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/tss.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/versions.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/x509.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/api_ref/zfec.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/authors.txt
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/building.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/cli.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/contents.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/credits.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/deprecated.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/dev_ref/configure.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/dev_ref/contents.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/dev_ref/continuous_integration.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/dev_ref/contributing.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/dev_ref/fuzzing.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/dev_ref/mistakes.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/dev_ref/oids.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/dev_ref/os.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/dev_ref/reading_list.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/dev_ref/release_process.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/dev_ref/test_framework.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/dev_ref/todo.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/goals.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/hardware_acceleration.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/index.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/migration_guide.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/old_news.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/openssl_migration_guide.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/packaging.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/pgpkey.txt
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/roadmap.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/security.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/sem_ver.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/side_channels.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/handbook/support.rst
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/license.txt
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/news.txt
rm -f %{buildroot}*/usr/share/doc/botan-3.3.0/pgpkey.txt

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libbotan-3.so.3
/usr/lib64/libbotan-3.so.3.3.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-Botan-soname2/746f79eacfdbe5f1af1553042b17fc2c3c1c59c7
